### ISSUE TITLE
Kernel crashes on pressing TAB

### ISSUE THREAD

**Issue by tbhaxor** [jupyter-xeus/xeus-cling#330] opened 2020-04-07 13:14 UTC
Steps to reproduce
**CELL1**
```cpp
#include "iostream"
```
**CELL2**
```cpp
std::<TAB><TAB>
```

The kernel crashes after this.

**Comment by SylvainCorlay** [comment] 2020-04-07 13:23
Thanks @tbhaxor. Closing as a duplicate of https://github.com/jupyter-xeus/xeus-cling/issues/41.

**Closed by SylvainCorlay** 2020-04-07 13:23 UTC
