### ISSUE TITLE
error: function definition is not allowed here

### ISSUE THREAD

**Issue by DYFeng** [jupyter-xeus/xeus-cling#370] opened 2020-12-06 16:58 UTC
```C++
int N = 300;
void test(){}
```

Output:
```bash
input_line_41:3:12: error: function definition is not allowed here
void test(){}
           ^
```

What's just happened?

**Comment by martinRenou** [comment] 2020-12-07 07:32
It's a duplicate of #333, the important part there is 
> please be sure to define your function in a separate cell with no code before the definition

**Closed** 2020-12-08 06:44 UTC
